#포트
server:
  port: 8082

spring: 
  #database 연동
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 4986
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/   # 기본 폴더 위치
    suffix: .html                   # 파일 확장자
    enabled: true
  devtools:
    restart: 
       enabled: true
    livereload:
       enabled: true   
  #spring data jpa 설정  MySQL5InnoDBDialect(mysql5 버전)
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  
    open-in-view: false
    show-sql: true
    hibernate: 
       ddl-auto: update 

  #oauth2 연동 설정(로그인 api)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 563100b444f6f0b3713610c52f6e6d4d
            client-secret: PCViwf16HFhcF35uJq9sPU0cYWt6QLhE
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8082/login/oauth2/code/kakao"
            client-name: Kakao
            scope:
            - profile_nickname
            - account_email
          naver:
            client-id: wPQWrtbCYIc7HxgGH_vW
            client-secret: 5jQsoHv3Q0 
            scope:
              - name
              - email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/naver
            client-name: Naver
            client-authentication-method: client_secret_post
          google:
            client-id: <구글 아이디>
            client-secret: <구글 비밀번호>
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/google
            client-name: Google
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

# Spring Security 디버그 설정 추가
logging:
  level:
    "[org.springframework.security]": DEBUG