#포트 설정
server:
  port: 80



spring:
  
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/   # 기본 폴더 위치
    suffix: .html                   # 파일 확장자
    enabled: true
  devtools:
    restart: 
       enabled: true
    livereload:
       enabled: true   
  #spring data jpa 설정  MySQL5InnoDBDialect(mysql5 버전)
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  
    open-in-view: false
    show-sql: true
    hibernate: 
       ddl-auto: update  
  web:
    resources:
      static-locations: 
        - classpath:/static/     # 기존 정적 리소스 경로
        - file:/works/img
   #oauth2 연동 설정(로그인 api)
   #database 연동
  
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://modamarthall.store/login/oauth2/code/kakao"
            client-name: Kakao
            scope:
            - profile_nickname
            - account_email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET} 
            scope:
              - name
              - email
            authorization-grant-type: authorization_code
            redirect-uri: http://modamarthall.store/login/oauth2/code/naver
            client-name: Naver
            client-authentication-method: client_secret_post
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: http://modamarthall.store/login/oauth2/code/google
            client-name: Google
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}          
  #spirng email 전송
  mail:
    host: smtp.gmail.com
    port: 587
    username: modamarthall@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from-address: modamArthall@gmail.com



# Spring Security 디버그 설정 추가
logging:
  level:
    "[org.springframework.security]": DEBUG

# 포트원
api:
  key: ${PORTONE_API_KEY}
  secret: ${PORTONE_API_SECRET}
