#포트 설정
server:
  port: 8082



spring: 
  #database 연동
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 5357
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/   # 기본 폴더 위치
    suffix: .html                   # 파일 확장자
    enabled: true
  devtools:
    restart: 
       enabled: true
    livereload:
       enabled: true   
  #spring data jpa 설정  MySQL5InnoDBDialect(mysql5 버전)
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  
    open-in-view: false
    show-sql: true
    hibernate: 
       ddl-auto: update  
  web:
    resources:
    
      static-locations: 
        - classpath:/static/     # 기존 정적 리소스 경로
        - file:./uploads/  
# 파일 업로드 설정
file:
  upload-dir: ./uploads/
  #oauth2 연동 설정(로그인 api)
security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: ${KAKAO_CLIENT_ID}
          client-secret: ${KAKAO_CLIENT_SECRET}
          client-authentication-method: post
          authorization-grant-type: authorization_code
          redirect-uri: "http://localhost:8082/login/oauth2/code/{registrationId}"
          scope: profile
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}
          client-authentication-method: client_secret_post
          authorization-grant-type: authorization_code
          redirect-uri: "http://localhost:8082/login/oauth2/code/{registrationId}"
          scope: id, name, email, mobile
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: id

# Spring Security 디버그 설정 추가
logging:
  level:
    "[org.springframework.security]": DEBUG
